# This workflow checks out the grafana-build repository, then builds, packages, and uploads Grafana to GCS.
name: "[RGM] Build and Package"
on:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
      - 'v*.*.*'
concurrency:
  group: rgm-build-package-${{ github.event.number }}
jobs:
  build:
    name: Package and upload a grafana.tar.gz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: grafana/grafana-build
          ref: add-package-publish-action
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'
      - name: Build Backend
        uses: ./actions/package/publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
        with:
          distros: 'linux/amd64,linux/arm64'
          enterprise: true
          grafana_ref: ${{ github.sha }}
          enterprise_ref: ${{ github.head_ref }}
          gcp_service_account_key_base64: ${{ secrets.RGM_GCP_KEY_BASE64 }}
          destination: ${{ secrets.RCM_DESTINATION }}/${{ github.event_name }}
